import { Category, Product } from "../projects/types";

export const FILTERS: Category[] = [
    "All",
    "Hardscape",
    "Facedes",
    "Renovation",
    "Finishing Decor",
    "Raised Floor",
];

export const PRODUCTS: Product[] = [
    {
        id: "ARCADE",
        name: "Decorative Arched Colonnade",
        category: "Finishing Decor", // "Facedes",
        images: [
            { src: "/COCA_024.webp" },
            { src: "/COCA_019.webp" },
            { src: "/COCO_020.webp" },
            { src: "/IMG_2220.JPG" },
            { src: "/IMG_2227.JPG" },
            { src: "/IMG_2290.JPG" },
            { src: "/IMG_2295.JPG" },
            { src: "/IMGNIGHT.jpeg" },
        ],
        description: "Decorative stone cladding engraving",
        details:
            "Finely detailed with a harminonius blend of classical geometry and ornamental artistry that gave the structure a timless,dignified presence.",
    },
    {
        id: "KFU",
        name: "King Faisal University",
        category: "Hardscape", //finishing and decor
        images: [
            { src: "/23--1.jpg" },
            { src: "/herobg.webp" },
            { src: "/image67.webp" },
            { src: "/IMG_1140.JPG" },
            { src: "/(59) - 1.jpg" },
            { src: "/PAIN_059.webp" },
            { src: "/PAAL_056.webp" },
            { src: "/PAPL_045.webp" },
            { src: "/PAPL_038.webp" },
            { src: "/IMG_1139.webp" },
            { src: "/PLWI_046.webp" },
            { src: "/PLST_040.webp" },
            { src: "/IMG_0649.webp" },
            { src: "/DOBU_042.webp" },
            { src: "/ROLA_044.webp" },
        ],
        description: "Designing supplying crafting and constructing.",
        details:
            "Engineered for maximum sustainability while maintaining an artistic design.",
    },
    {
        id: "TTP",
        name: "TV Tower Plaza",
        category: "Hardscape",
        images: [
            { src: "/IMG_0064.webp" },
            { src: "/ROPL_061.webp" },
            { src: "/ROPL_062.webp" },
            { src: "/ROPL_063.webp" },
            { src: "/ROPL_072.webp" },
            { src: "/ROPL_073.webp" },
            { src: "/ROPL_064.webp" },
            { src: "/ROPL_066.webp" },
            { src: "/BLMO_068.webp" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "BackYard",
        name: "Backyard Decor and Landscape",
        category: "Renovation",
        images: [
            { src: "/BY7.jpeg" },
            { src: "/BY3.jpeg" },
            { src: "/BY4.jpeg" },
            { src: "/BY5.jpeg" },
            { src: "/BY6.jpeg" },
            { src: "/BY1.jpeg" },
            { src: "/BY2.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "Bus",
        name: "Riyadh bus stations",
        category: "Hardscape",
        images: [
            { src: "/bus1.jpeg" },
            { src: "/bus2.jpeg" },
            { src: "/bus3.jpeg" },
            { src: "/busirl1.jpeg" },
            { src: "/busirl2.jpeg" },
            { src: "/busirl3.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "Vrock",
        name: "V-Rock decor",
        category: "Finishing Decor",
        images: [
            { src: "/Vrock3.2.jpeg" },
            { src: "/Vrock1.jpeg" },
            { src: "/Vrock2.jpeg" },
            { src: "/Vrock4.jpeg" },
            { src: "/Vrock5.2.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "Block",
        name: "Residential porcelain facede",
        category: "Facedes",
        images: [
            { src: "/SQ1.jpeg" },
            { src: "/SQ2.jpeg" },
            { src: "/SQ4.jpeg" },
            { src: "/SQ5.jpeg" },
            { src: "/SQ6.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "SV",
        name: "Residential Landscape and Fence",
        category: "Finishing Decor",
        images: [
            { src: "/2v7.jpeg" },
            { src: "/2v1.jpeg" },
            { src: "/2v2.jpeg" },
            { src: "/2v4.jpeg" },
            { src: "/2v5.jpeg" },
            { src: "/2v6.jpeg" },
            { src: "/2v8.jpeg" },
            { src: "/2v9.jpeg" },
            { src: "/2v10.jpeg" },
            { src: "/2v11.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "RF",
        name: "Work office Raised Floor",
        category: "Raised Floor",
        images: [
            { src: "/RF1.jpeg" },
            { src: "/RF2.jpeg" },
            { src: "/RF1.2.jpeg" },
            { src: "/RF4.jpeg" },
            { src: "/RF5.jpeg" },
            { src: "/RF6.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "Fence",
        name: "Rock fence",
        category: "Finishing Decor",
        images: [
            { src: "/F1.JPG" },
            { src: "/F2.JPG" },
            { src: "/F3.webp" },
            { src: "/F4.webp" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "Lime",
        name: "Limestone Hardscape",
        category: "Hardscape",
        images: [
            { src: "/hs2.jpeg" },
            { src: "/hs5.jpeg" },
            { src: "/hs3.jpeg" },
            { src: "/28s.webp" },
            { src: "/38s.webp" },
            { src: "/30s.webp" },
            { src: "/hs1.jpeg" },
            { src: "/hs7.jpeg" },
            { src: "/hs4.jpeg" },

            { src: "/2s.webp" },
            { src: "/1s.webp" },

            { src: "/hs6.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "marble",
        name: "Artistic marble usage  ",
        category: "Facedes",
        images: [
            { src: "/marb3.jpeg" },
            { src: "/marb1.jpeg" },
            { src: "/marb2.jpeg" },
            { src: "/marb4.jpeg" },
            { src: "/marb5.jpeg" },
        ],
        description: ".",
        details: ".",
    },
    {
        id: "renoV",
        name: "Villa Renovation",
        category: "Renovation",
        images: [{ src: "/RenoV2.jpeg" }, { src: "/RenoV1.jpeg" }],
        description: ".",
        details: ".",
    },
    {
        id: "renoV2",
        name: "Villa Renovation",
        category: "Renovation",
        images: [
            { src: "/reno2v7.jpeg" },
            { src: "/reno2v1.jpeg" },
            { src: "/reno2v2.jpeg" },
            { src: "/reno2v3.jpeg" },
            { src: "/reno2v5.jpeg" },
            { src: "/reno2v6.jpeg" },
            { src: "/reno2v4.jpeg" },
        ],
        description: ".",
        details: ".",
    },
];
