import { Category, Product } from "../projects/types";

export const FILTERS: Category[] = [
    "All",
    "Hardscape",
    "Facedes",
    "Renovation",
    "Finishing Decor",
    "Raised Floor",
];

export const PRODUCTS: Product[] = [
    {
        id: "ARCADE",
        name: "Projects.products.ARCADE.name",
        category: "Finishing Decor", // "Facedes",
        images: [
            { src: "/COCA_024.webp" },
            { src: "/COCA_019.webp" },
            { src: "/COCO_020.webp" },
            { src: "/IMG_2220.JPG" },
            { src: "/IMG_2227.JPG" },
            { src: "/IMG_2290.JPG" },
            { src: "/IMG_2295.JPG" },
            { src: "/IMGNIGHT.jpeg" },
        ],
        description: "Projects.products.ARCADE.description",
        details:
            "Projects.products.ARCADE.details",
    },
    {
        id: "KFU",
        name: "Projects.products.KFU.name",
        category: "Hardscape", //finishing and decor
        images: [
            { src: "/23-1.jpg" },
            { src: "/herobg.webp" },
            { src: "/image67.webp" },
            { src: "/IMG_1140.JPG" },
            { src: "/59-1.jpg" },
            { src: "/PAIN_059.webp" },
            { src: "/PAAL_056.webp" },
            { src: "/PAPL_045.webp" },
            { src: "/PAPL_038.webp" },
            { src: "/IMG_1139.webp" },
            { src: "/PLWI_046.webp" },
            { src: "/PLST_040.webp" },
            { src: "/IMG_0649.webp" },
            { src: "/DOBU_042.webp" },
            { src: "/ROLA_044.webp" },
        ],
        description: "Projects.products.KFU.description",
        details:
            "Projects.products.KFU.details",
    },
    {
        id: "TTP",
        name: "Projects.products.TTP.name",
        category: "Hardscape",
        images: [
            { src: "/IMG_0064.webp" },
            { src: "/ROPL_061.webp" },
            { src: "/ROPL_062.webp" },
            { src: "/ROPL_063.webp" },
            { src: "/ROPL_072.webp" },
            { src: "/ROPL_073.webp" },
            { src: "/ROPL_064.webp" },
            { src: "/ROPL_066.webp" },
            { src: "/BLMO_068.webp" },
        ],
        description: "Projects.products.TTP.description",
        details: "Projects.products.TTP.details",
    },
    {
        id: "BackYard",
        name: "Projects.products.BackYard.name",
        category: "Renovation",
        images: [
            { src: "/BY7.jpeg" },
            { src: "/BY3.jpeg" },
            { src: "/BY4.jpeg" },
            { src: "/BY5.jpeg" },
            { src: "/BY6.jpeg" },
            { src: "/BY1.jpeg" },
            { src: "/BY2.jpeg" },
        ],
        description: "Projects.products.BackYard.description",
        details: "Projects.products.BackYard.details",
    },
    {
        id: "Bus",
        name: "Projects.products.Bus.name",
        category: "Hardscape",
        images: [
            { src: "/bus1.jpeg" },
            { src: "/bus2.jpeg" },
            { src: "/bus3.jpeg" },
            { src: "/busirl1.jpeg" },
            { src: "/busirl2.jpeg" },
            { src: "/busirl3.jpeg" },
        ],
        description: "Projects.products.Bus.description",
        details: "Projects.products.Bus.details",
    },
    {
        id: "Vrock",
        name: "Projects.products.Vrock.name",
        category: "Finishing Decor",
        images: [
            { src: "/Vrock3.2.jpeg" },
            { src: "/Vrock1.jpeg" },
            { src: "/Vrock2.jpeg" },
            { src: "/Vrock4.jpeg" },
            { src: "/Vrock5.2.jpeg" },
        ],
        description: "Projects.products.Vrock.description",
        details: "Projects.products.Vrock.details",
    },
    {
        id: "Block",
        name: "Projects.products.Block.name",
        category: "Facedes",
        images: [
            { src: "/SQ1.jpeg" },
            { src: "/SQ2.jpeg" },
            { src: "/SQ4.jpeg" },
            { src: "/SQ5.jpeg" },
            { src: "/SQ6.jpeg" },
        ],
        description: "Projects.products.Block.description",
        details: "Projects.products.Block.details",
    },
    {
        id: "SV",
        name: "Projects.products.SV.name",
        category: "Finishing Decor",
        images: [
            { src: "/2v7.jpeg" },
            { src: "/2v1.jpeg" },
            { src: "/2v2.jpeg" },
            { src: "/2v4.jpeg" },
            { src: "/2v5.jpeg" },
            { src: "/2v6.jpeg" },
            { src: "/2v8.jpeg" },
            { src: "/2v9.jpeg" },
            { src: "/2v10.jpeg" },
            { src: "/2v11.jpeg" },
        ],
        description: "Projects.products.SV.description",
        details: "Projects.products.SV.details",
    },
    {
        id: "RF",
        name: "Projects.products.RF.name",
        category: "Raised Floor",
        images: [
            { src: "/RF1.jpeg" },
            { src: "/RF2.jpeg" },
            { src: "/RF1.2.jpeg" },
            { src: "/RF4.jpeg" },
            { src: "/RF5.jpeg" },
            { src: "/RF6.jpeg" },
        ],
        description: "Projects.products.RF.description",
        details: "Projects.products.RF.details",
    },
    {
        id: "Fence",
        name: "Projects.products.Fence.name",
        category: "Finishing Decor",
        images: [
            { src: "/F1.JPG" },
            { src: "/F2.JPG" },
            { src: "/F3.webp" },
            { src: "/F4.webp" },
        ],
        description: "Projects.products.Fence.description",
        details: "Projects.products.Fence.details",
    },
    {
        id: "Lime",
        name: "Projects.products.Lime.name",
        category: "Hardscape",
        images: [
            { src: "/hs2.jpeg" },
            { src: "/hs5.jpeg" },
            { src: "/hs3.jpeg" },
            { src: "/28s.webp" },
            { src: "/38s.webp" },
            { src: "/30s.webp" },
            { src: "/hs1.jpeg" },
            { src: "/hs7.jpeg" },
            { src: "/hs4.jpeg" },

            { src: "/2s.webp" },
            { src: "/1s.webp" },

            { src: "/hs6.jpeg" },
        ],
        description: "Projects.products.Lime.description",
        details: "Projects.products.Lime.details",
    },
    {
        id: "marble",
        name: "Projects.products.marble.name",
        category: "Facedes",
        images: [
            { src: "/marb3.jpeg" },
            { src: "/marb1.jpeg" },
            { src: "/marb2.jpeg" },
            { src: "/marb4.jpeg" },
            { src: "/marb5.jpeg" },
        ],
        description: "Projects.products.marble.description",
        details: "Projects.products.marble.details",
    },
    {
        id: "renoV",
        name: "Projects.products.renoV.name",
        category: "Renovation",
        images: [{ src: "/RenoV2.jpeg" }, { src: "/RenoV1.jpeg" }],
        description: "Projects.products.renoV.description",
        details: "Projects.products.renoV.details",
    },
    {
        id: "renoV2",
        name: "Projects.products.renoV2.name",
        category: "Renovation",
        images: [
            { src: "/reno2v7.jpeg" },
            { src: "/reno2v1.jpeg" },
            { src: "/reno2v2.jpeg" },
            { src: "/reno2v3.jpeg" },
            { src: "/reno2v5.jpeg" },
            { src: "/reno2v6.jpeg" },
            { src: "/reno2v4.jpeg" },
        ],
        description: "Projects.products.renoV2.description",
        details: "Projects.products.renoV2.details",
    },
];
